#!/bin/sh

# callsyntax: $0 $1=IFNAME $2=OPTIONS $3=OP

IFNAME=$1
OPTIONS=$2
OP=$3
SERVICE_NAME="hostapd"
SERVICE_PATH="/tmp/$SERVICE_NAME"
LOG_PREFIX="$SERVICE_NAME($IFNAME):"
NOTIFY_PATH="$SERVICE_PATH/$IFNAME"
HOSTAPD_EXEC="hostapd -- $OPTIONS -B"

if [ ! -d $SERVICE_PATH ]; then
    mkdir $SERVICE_PATH
fi

start() {
    echo -e "\033[32m$LOG_PREFIX starting($HOSTAPD_EXEC)\033[0m"
    ifconfig -a
    start-stop-daemon -S -x $HOSTAPD_EXEC
    case $? in
        0)
            network_notifier $NOTIFY_PATH "started"
            ;;
        *)
            echo -e "\033[31m$LOG_PREFIX failed($?)\033[0m"
            network_notifier $NOTIFY_PATH "failed"
            ;;
    esac
}

stop() {
    echo -e "\033[32m$LOG_PREFIX stopping($HOSTAPD_EXEC)\033[0m"
    start-stop-daemon -K -q -x $HOSTAPD_EXEC
    case $? in
        0 | 1)
            ;;
        *)
            echo -e "\033[31m$LOG_PREFIX failed($?)\033[0m"
            ;;
    esac
    sleep 5
    network_notifier $NOTIFY_PATH "stopped"
}

status() {
    echo -e "\033[31m$LOG_PREFIX not yet supported\033[0m"
}

if [ -z $IFNAME ]; then
    echo -e "Usage: $0 ifname options [start|stop|status]"
    exit 1
fi

case $OP in
    start|stop|status)
        $OP
        ;;
    *)
        echo -e "Usage: $0 ifname options [start|stop|status]"
        exit 1
        ;;
esac

exit $?
