#!/bin/sh

# callsyntax: $0 $1=IFNAME $2=OP

IFNAME=$1
OP=$2
SERVICE_NAME="minissdpd"
SERVICE_PATH="/tmp/$SERVICE_NAME/$IFNAME"
LOG_PREFIX="$SERVICE_NAME($IFNAME):"
NOTIFY_PATH="$SERVICE_PATH"
ARGS="-i $IFNAME"
EXEC="minissdpd -- $ARGS"

start() {
    start-stop-daemon -S -x $EXEC
    case $? in
        0)
            echo -e "\033[32m$LOG_PREFIX started\033[0m"
            network_notifier $NOTIFY_PATH "started"
            ;;
        *)
            echo -e "\033[31m$LOG_PREFIX failed($?)\033[0m"
            network_notifier $NOTIFY_PATH "failed"
            ;;
    esac
}

stop() {
    start-stop-daemon -K -q -x $EXEC
    case $? in
        0)
            echo -e "\033[32m$LOG_PREFIX stopped\033[0m"
            ;;
        *)
            echo -e "\033[31m$LOG_PREFIX failed($?)\033[0m"
            ;;
    esac
    network_notifier $NOTIFY_PATH "stopped"
}

restart() {
    stop
    start
}

case $OP in
    start|stop|restart)
        $OP
        ;;
    *)
        echo -e "Usage: $0 ifname [start|stop|restart]"
        exit 1
        ;;
esac

exit $?
