#!/bin/sh
#description: startup script for UPnPDiscovery daemon
#processname: miniupnpd

. /etc/miniupnpd/miniupnpd.conf
. /etc/miniupnpd/miniupnpcfg
set -e

NAME=upnpdiscovery
MINIUPNPD=/usr/sbin/miniupnpd
ARGS='-f /etc/miniupnpd/miniupnpd.conf'
PID_FILE=/var/run/miniupnpd.pid
EXE_NAME=miniupnpd


test -f $MINIUPNPD || exit 0

start() {
        if [ "$enable_upnp" = yes ]; then
		echo -e "Starting $NAME"
       	 	start-stop-daemon -b -q -S --pidfile $PID_FILE -x $MINIUPNPD -- $ARGS
        	echo -e "$NAME is now running"
	else
		echo -e "$NAME is Disabled"
	fi
}

stop() {
        echo -e "Stopping $NAME"
	if [ -f "$PID_FILE" ]; then
		_pid=$(cat $PID_FILE 2>/dev/null)
        	if [ "$_pid" ]; then
			kill -INT $_pid
        	else
                	echo -e "$NAME is not running. Stop failed"
        	fi
		rm -f $PID_FILE
	else
		echo -e "$NAME is not running. Stop failed"
	fi
}

case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  restart|reload|force-reload)
        echo -e "Reloading $NAME"
	if [ -f "$PID_FILE" ]; then
		_pid=$(cat $PID_FILE 2>/dev/null)
        	if [ "$_pid" ]; then
			kill -INT $_pid
			echo -e "$NAME is now stopped"
			start
        	else
                	echo -e "$NAME is not running. Reloading failed"
        	fi
	else
		echo -e "$NAME is not running. Stopping is not required"
		start	
	fi
        ;;
  *)
        echo -e "Usage: /etc/ini.d/$EXE_NAME {start|stop|restart|reload|force-reload}"
        exit 1
        ;;
esac
exit 0

